export type SkillFormStateObj = {
    title: string,
    desc: string,
    useDifficulty: number,
    actionPointCost: number,
    cardCost: any,
    coolDown: number,
    range: number,
    areaType: string,
    areaOfEffect: number,
    target: string,
    affected: string,
    damage: number,
    damageType: string,
    requiredFocus: any,
    mainFocus: string,
    setStatus: string,
    statusDuration: number,
}