export enum StatusEnum {
    Acid = 'Acid',
    AnimalSpeak = 'Animal Speak',
    Animated = 'Animated',
    AnimateElement = 'Animate Element',
    AquaticAdaptation = 'AquaticAdaptation',
    Armored = 'Armored',
    Atrophy = 'Atrophy',
    BallOfLight = 'Ball of Light',
    BareBlock = 'Bare Block',
    BarkSkin = 'Bark Skin',
    Befriended = 'Befriended',
    BendLight = 'Bend Light',
    BendSteel = 'Bend Steel',
    Bleeding = 'Bleeding',
    Blinded = 'Blinded',
    BludgeonArmor = 'Bludgeon Armor',
    Blur = 'Blur',
    BoneCage = 'Bone Cage',
    BreakingBlock = 'Breaking Block',
    BreathingBubble = 'Breathing Bubble',
    BroadSwings = 'BroadSwings',
    Burning = 'Burning',
    Chickenified = 'Chickenified',
    Chilled = 'Chilled',
    Concussed = "Concussed",
    Crippled = 'Crippled',
    Crushed = 'Crushed',
    Cursed = 'Cursed',
    Dazed = 'Dazed',
    Decay = 'Decay',
    Deaf = 'Deaf',
    DemonFists = 'Demon Fists',
    Diseased = 'Diseased',
    ElementCoating = 'Element Coating',
    Electrified = 'Electrified',
    Enlarged = 'Enlarged',
    Enraged = 'Enraged',
    Entangled = 'Entangled',
    ErraticWisp = 'ErraticWisp',
    Evasive = 'Evasive',
    EverlastingRest = 'Everlasting Rest',
    Farsighted = 'Farsighted',
    Fear = 'Fear',
    FlamingTongues = 'Flaming Tongues',
    FlamingWeapon = 'Flaming Weapon',
    Flight = 'Flight',
    Fortified = 'Fortified',
    FreezingWeapon = 'Freezing Weapon',
    Frozen = 'Frozen',
    GentleRepose = 'Gentle Repose',
    GravityPulled = 'Gravity Pulled',
    GuardianAngel = 'Guardian Angel',
    Hardened = 'Hardened',
    HarnessMomentum = 'Harness Momentum',
    Healing = 'Healing',
    HeartOfSteel = 'Heart of Steel',
    HeavyHitter = 'Heavy Hitter',
    HuntersMark = "Hunter's Mark",
    ImmortalSummon = 'Immortal Summon',
    IncreasedMovement = 'Increased Movement',
    InvestitureOfStone = 'Investiture of Stone',
    Invisible = 'Invisible',
    Juggler = 'Juggler',
    Knocked = 'Knocked',
    LessMass = 'Less Mass',
    Levitate = 'Levitate',
    Light = 'Light',
    MakeshiftWeapon = 'Makeshift Weapon',
    MedusaHead = 'Medusa Head',
    MindControlled = 'Mind Controlled',
    Misdirection = 'Misdirection',
    MoreMass = 'More Mass',
    NightVision = 'Night Vision',
    NimbleFingers = 'Nimble Fingers',
    None = 'None',
    NullifyGravity = 'Nullify Gravity',
    Oiled = 'Oiled',
    Paralysis = 'Paralysis',
    PlantSpeak = 'Plant Speak',
    PoisonResist = 'Poison Resist',
    Poisoned = 'Poisoned',
    Provoked = 'Provoked',
    QuickDraw = 'Quick Draw',
    Rallied = 'Rallied',
    Random = 'Random',
    Regenerate = 'Regenerate',
    Reflect = 'Reflect',
    ReverseGravity = 'Reverse Gravity',
    SensoryCompensation = 'Sensory Compensation',
    ShareDamage = 'Share Damage',
    Shocked = 'Shocked',
    ShortWalk = 'Short Walk',
    Shrapnel = 'Shrapnel',
    Silenced = 'Silenced',
    SkinMod = 'Skin Mod',
    Sleep = 'Sleep',
    SmokeShroud = 'Smoke Shroud',
    SoftHands = 'Soft Hands',
    SoulMate = 'Soul Mate',
    SparkingStrikes = 'Sparking Strikes',
    SpiderLegs = 'Spider Legs',
    Stasis = 'Stasis',
    Stunned = 'Stunned',
    StructuralWeakness = 'Structural Weakness',
    Suffocating = 'Suffocating',
    Supercharged = 'Supercharged',
    Swimmer = 'Swimmer',
    ThickOfTheFight = 'Thick of the Fight',
    ThunderStep = 'ThunderStep',
    TightGrip = 'Tight Grip',
    Tracking = 'Tracking',
    TreeStride = 'TreeStride',
    VampiricAura = 'Vampiric Aura',
    VenomCoating = 'Venom Coating',
} 

export const statusArray: Array<StatusEnum> = [
    StatusEnum.Acid,
    StatusEnum.AnimalSpeak,
    StatusEnum.AnimateElement,
    StatusEnum.Animated,
    StatusEnum.AquaticAdaptation,
    StatusEnum.Armored,
    StatusEnum.Atrophy,
    StatusEnum.BallOfLight,
    StatusEnum.BareBlock,
    StatusEnum.BarkSkin,
    StatusEnum.Befriended,
    StatusEnum.BendLight,
    StatusEnum.BendSteel,
    StatusEnum.Bleeding,
    StatusEnum.Blinded,
    StatusEnum.BludgeonArmor,
    StatusEnum.Blur,
    StatusEnum.BoneCage,
    StatusEnum.BreakingBlock,
    StatusEnum.BreathingBubble,
    StatusEnum.BroadSwings,
    StatusEnum.Burning,
    StatusEnum.Chickenified,
    StatusEnum.Chilled,
    StatusEnum.Concussed,
    StatusEnum.Crippled,
    StatusEnum.Crushed,
    StatusEnum.Cursed,
    StatusEnum.Dazed,
    StatusEnum.Decay,
    StatusEnum.Deaf,
    StatusEnum.DemonFists,
    StatusEnum.Diseased,
    StatusEnum.ElementCoating,
    StatusEnum.Electrified,
    StatusEnum.Enlarged,
    StatusEnum.Enraged,
    StatusEnum.Entangled,
    StatusEnum.ErraticWisp,
    StatusEnum.Evasive,
    StatusEnum.EverlastingRest,
    StatusEnum.Farsighted,
    StatusEnum.Fear,
    StatusEnum.FlamingTongues,
    StatusEnum.FlamingWeapon,
    StatusEnum.Flight,
    StatusEnum.Fortified,
    StatusEnum.FreezingWeapon,
    StatusEnum.Frozen,
    StatusEnum.GentleRepose,
    StatusEnum.GravityPulled,
    StatusEnum.GuardianAngel,
    StatusEnum.Hardened,
    StatusEnum.HarnessMomentum,
    StatusEnum.Healing,
    StatusEnum.HeartOfSteel,
    StatusEnum.HeavyHitter,
    StatusEnum.HuntersMark,
    StatusEnum.ImmortalSummon,
    StatusEnum.IncreasedMovement,
    StatusEnum.InvestitureOfStone,
    StatusEnum.Invisible,
    StatusEnum.Juggler,
    StatusEnum.Knocked,
    StatusEnum.LessMass,
    StatusEnum.Levitate,
    StatusEnum.Light,
    StatusEnum.MakeshiftWeapon,
    StatusEnum.MedusaHead,
    StatusEnum.MindControlled,
    StatusEnum.Misdirection,
    StatusEnum.MoreMass,
    StatusEnum.NightVision,
    StatusEnum.NimbleFingers,
    StatusEnum.None,
    StatusEnum.NullifyGravity,
    StatusEnum.Oiled,
    StatusEnum.Paralysis,
    StatusEnum.PlantSpeak,
    StatusEnum.PoisonResist,
    StatusEnum.Poisoned,
    StatusEnum.Provoked,
    StatusEnum.QuickDraw,
    StatusEnum.Rallied,
    StatusEnum.Random,
    StatusEnum.Regenerate,
    StatusEnum.Reflect,
    StatusEnum.ReverseGravity,
    StatusEnum.SensoryCompensation,
    StatusEnum.ShareDamage,
    StatusEnum.Shocked,
    StatusEnum.ShortWalk,
    StatusEnum.Shrapnel,
    StatusEnum.Silenced,
    StatusEnum.SkinMod,
    StatusEnum.Sleep,
    StatusEnum.SmokeShroud,
    StatusEnum.SoftHands,
    StatusEnum.SoulMate,
    StatusEnum.SparkingStrikes,
    StatusEnum.SpiderLegs,
    StatusEnum.Stasis,
    StatusEnum.Stunned,
    StatusEnum.StructuralWeakness,
    StatusEnum.Suffocating,
    StatusEnum.Supercharged,
    StatusEnum.Swimmer,
    StatusEnum.ThickOfTheFight,
    StatusEnum.ThunderStep,
    StatusEnum.TightGrip,
    StatusEnum.Tracking,
    StatusEnum.TreeStride,
    StatusEnum.VampiricAura,
    StatusEnum.VenomCoating,
] 